services:
    migrate:
        build:
            context: .
            dockerfile: Dockerfile
            target: builder
        env_file:
            - .env
        volumes:
            - ./server-data:/app/data
            - ./drizzle:/app/drizzle
            - ./drizzle.config.ts:/app/drizzle.config.ts
        command: ["bun", "run", "db:migrate"]

    server:
        build: .
        env_file:
            - .env
        environment:
            PORT: 3000
        volumes:
            - ./server-data:/app/data
        depends_on:
            migrate:
                condition: service_completed_successfully
        networks:
            - appnet

    nginx:
        image: nginx:1.30.2-alpine
        depends_on:
            server:
                condition: service_started
        ports:
            - "[::]:80:80"
            - "[::]:443:443"
        volumes:
            - ${NGINX_CONFIG}:/etc/nginx/conf.d/default.conf:ro
            - /etc/letsencrypt:/etc/letsencrypt
        networks:
            - appnet

networks:
    appnet:
        enable_ipv6: true
        ipam:
          config:
              - subnet: "fd00:cafe:babe:1::/64"
