services:
    migrate:
        build:
            context: .
            dockerfile: Dockerfile
            target: builder
        env_file:
            - .env
        volumes:
            - ${BUCMARC_DATA_DIR:-./server-data}:/app/data
            - ./drizzle:/app/drizzle
            - ./drizzle.config.ts:/app/drizzle.config.ts
        command:
            - bun
            - run
            - ${DRIZZLE_UDATE_DB_COMMAND}
        logging:
            driver: json-file
            options:
                max-size: "5m"
                max-file: "3"

    server:
        build: .
        env_file:
            - .env
        environment:
            PORT: 3000
            FORCE_COLOR: 1
        volumes:
            - ${BUCMARC_DATA_DIR:-./server-data}:/app/data
            - ./public:/app/public
        depends_on:
            migrate:
                condition: service_completed_successfully
        networks:
            reverse-proxy:
                aliases:
                    - bucmarc
        logging:
            driver: json-file
            options:
                max-size: "20m"
                max-file: "5"

networks:
    reverse-proxy:
        external: true
